### ISSUE TITLE
Data Driven Mine Development - Team Expansion

### ISSUE THREAD

**Issue by bcdevex** [bcgov/mds#36]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/swu/opp-year-1---data-driven-mines-development">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/swu/opp-year-1---data-driven-mines-development">visit the opportunity page</a>. The opportunity closes on <b>Wednesday, September 5, 2018</b>.</p>

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by ActionAnalytics** [comment]
Autogenerated artifact closed
