### ISSUE TITLE
Python mds_backend failing on docker

### ISSUE THREAD

**Issue by cedar-technologies** [bcgov/mds#386]
Python mds_backend failing on docker

**To Reproduce**

```
git checkout master
docker-compose up  -d
```

```
git checkout develop
docker-compose up  -d
```

**Expected behavior**
mds_backend should run

**Screenshots**
![image](https://user-images.githubusercontent.com/12205969/50900603-8e1b8300-13ca-11e9-935f-b003796f10e6.png)

**Desktop (please complete the following information):**

* OS: Windows 10
* Docker: Docker Desktop Community - Version 2.0.0.0-win81 (29211)

**Comment by cedar-technologies** [comment]
logs:
![image](https://user-images.githubusercontent.com/12205969/50900910-755f9d00-13cb-11e9-943d-bb99cf89aa92.png)

**Comment by FreshGyan** [comment]
@cedar-technologies Hi There!
The error message indicates that the FLASK_APP environment variable was not supplied. If you take a look at bullet point number 2 under the USAGE readme, it instructs setting up `.env` files. If you would like to see what values should be in the `.env` files, there is an `.env-example` in the directory.

The container should behave as expected if you create a `.env` file with the required values. Let us know if that helps!

**Comment by cedar-technologies** [comment]
Hi @FreshGyan, thanks for the response. I had the .env set on my local repo, so that must be something else that I was doint wrong, I will resync the repo and restart fresh with windows instructions again. I'll try on osx environment too if I have time.

One suggestion could be to reorganize a bit the doc, the part that is accessible with open shift is in the middle and it's a bit confusing if you should do this steps or not. also it would be good to have a summary somewhere or the different component that compose the application. For instance I have no idea what keycloak was something simple like
* [keycloak](https://www.keycloak.org/) -  Access Management
* [Flask app](http://flask.pocoo.org/) - Python Rest api backend 
....
 so that the someone that looks at the project knows the stack right away ;-)

Thanks again,

I'll let you know once I have it running

**Comment by FreshGyan** [comment]
Hi @cedar-technologies Excellent suggestions! We've been trying to improve our documentation and this is really helpful. I will implement those as soon as I get the chance. :D

Let me know what the issue was and if you were able to resolve it.

**Comment by ActionAnalytics** [comment]
The configuration was set and the local environment was successfully instantiated.
